{% set name = "yews" %}
{% set version = "0.0.4" %}
{% set sha256 = "68d4660e1996508ea6515965b02dfd5b5e9bf73db99c1f5e8c17230e836f5b90" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}  

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:  
  host:
    - pip
    - python >=3.6
    - scipy
    - pytorch-cpu >1.0.0
  run:
    - python >=3.6
    - numpy
    - scipy
    - pytorch-cpu >1.0.0

test:
  imports:
    - yews

about:
  home: https://github.com/lijunzh/yews
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Yews: Your Earthquake Waveform Solutions.'

extra:
  recipe-maintainers:
    - lijunzh
