{% set name = "yews" %}
{% set version = "0.0.3" %}
{% set sha256 = "b3e5426603bd3818f13fc3dbd23876870345ba4d4c291563efa1cad2e7797a8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}  

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:  
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - pytorch-cpu >1.0.0

test:
  imports:
    - yews

about:
  home: https://github.com/lijunzh/yews
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Yews: Your Earthquake Waveform Solutions.'

extra:
  recipe-maintainers:
    - lijunzh
