{% set name = "yews" %}
{% set version = "0.0.6" %}
{% set sha256 = "4f262651634fbc847e12b47077a108727f79c50ea2d1b665b1ba7ac5c91e6abd" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}  

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:  
  host:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - python >=3.6
    - numpy
    - scipy
    - pytorch >=1.0.0
    - obspy
    - tqdm

test:
  imports:
    - yews

about:
  home: https://github.com/lijunzh/yews
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Yews: Your Earthquake Waveform Solutions.'

extra:
  recipe-maintainers:
    - lijunzh
