travis:
  secure:
    BINSTAR_TOKEN: RTJG5bGUtF+hh3/c1PKs3w94FJEdx7EGhWoTfGE3aLyjEZFVU8yz/hw3PUPl1Uz6T01SBMn6YcsnojsyZilWG4cAvt2tQl0kaCJOX0NiKKqBu19uTGxXJdcS0jC7jhHx12rfVM0Pt/tAQsQ+N4MNwthbba8qIP8l0V8Ko82nrU6v9q/zKKvB2xp4zq2sJXtiKA3gys4+iYZV9L8724EgJto984DlEWYgMHxRcKpMCN93pvRbsH+/w7FrpNUy0DDZSBHZqbwb0yutOJ2OlRbZEqZK6Qq2W0CBhSgly7KSup5t0BWJR6G7vHbbDL5vo7qd8TffUnEZ5n0Ojm3hTnPnTDMGBO4CKBFXNmVCzm6tqEysLUDflxWsp82GMU0uRjcZK56upk3Q17uvWjChw00LL8HTnU05hetlDdQpUNJwj2iUcvd+EOUNr749Ms70DG0KXwk1yNIjQNQgHyC3vN2wmopTvpWQVHt99fcpFfmw6M2d4f66+idNzSEQ0GszCbeZp/hEL9L7c7FzPLCWVyxE3QoiQJtiBTSLI2NQ97V+3TQb8ISrC27F36DJvMHg9n1vUXV4HxG/2nabiLy/fM+LvvhvfbtTTxkkGx8U6/tUqUx2upvFB1YTQGa/rHT74+4O2VwYrFuA/UMqSKi333HpyMJnUXazjDeWHRMut+pdWDE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
